version: "3"
networks: {}
services:
  bitcoind-1:
    links:
    - tor-1
    depends_on: 
    - tor-1
    restart: unless-stopped
    container_name: playground-bitcoind-1
    environment:
      - ARCH=${ARCH}
    build: 
      context: ./bitcoin-signet
      dockerfile: Dockerfile
      args:
        - ARCH=${ARCH}
    expose:
    - "38332"
    - "38333"
    - "38334"
    volumes:
      - type: bind
        source: ${PWD}/volumes/bitcoin_datadir-1
        target: /root/.bitcoin/
  lnd-1:
    links:
      - bitcoind-1
      - tor-1
    depends_on: 
      - bitcoind-1
      - tor-1
    environment:
      LND_ALIAS: 'play-cluster-0001'
      LND_LISTEN: 'playground-lnd-1:9735'
      LND_RPCLISTEN: 'playground-lnd-1:10009'
      LND_RESTLISTEN: 'playground-lnd-1:8080'
      zmqpubrawblock: 'tcp://playground-bitcoind-1:28332'
      zmqpubrawtx: 'tcp://playground-bitcoind-1:28333'
      torsocks: 'playground-tor-1:9050'
      torcontrol: 'playground-tor-1:9051'
      tlsextradomain: 'playground-lnd-1'
    restart: unless-stopped
    container_name: playground-lnd-1
    build: 
      context: ./lnd-signet
      dockerfile: Dockerfile
    expose:
    - 8080
    - 9735
    - 9911
    - 10009
    volumes:
      - type: bind
        source: ${PWD}/volumes/lnd_datadir-1
        target: /root/.lnd/
  tor-1:
      restart: unless-stopped
      container_name: playground-tor-1
      build:
        context: ./tor
        dockerfile: Dockerfile
      expose:
      - 9050
      - 9051
      volumes:
        - type: bind
          source: ${PWD}/volumes/tor_datadir-1
          target: /home/tor/.tor
        - type: bind
          source: ${PWD}/volumes/tor_torrcdir-1
          target: /usr/local/etc/tor
        - type: bind
          source: ${PWD}/volumes/tor_servicesdir-1
          target: /var/lib/tor/hidden_services  